# Generated by Django 4.2.3 on 2023-07-30 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(unique=True, verbose_name='Номер класса')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lang', 'language'), ('litr', 'literature'), ('math', 'mathematics'), ('hist', 'history'), ('bio', 'biology'), ('geo', 'geography'), ('physics', 'physics'), ('social', 'social studies'), ('comp', 'computer science'), ('chemistry', 'chemistry')], max_length=100, verbose_name='Название предмета')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.gradeclass', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='логин')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='пол')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('subjects', models.ManyToManyField(to='education.subject', verbose_name='Предметы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='логин')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='пол')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.gradeclass', verbose_name='Класс')),
                ('subjects', models.ManyToManyField(to='education.subject', verbose_name='Предметы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grade', models.FloatField(verbose_name='Общая успеваемость')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.pupil', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.assignment', verbose_name='Задание')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.pupil', verbose_name='Ученик')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.topic', verbose_name='Тема'),
        ),
    ]
