# Generated by Django 4.2.3 on 2023-07-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='login',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='class_number',
            field=models.PositiveIntegerField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], unique=True, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='grade_class',
            field=models.ForeignKey(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], on_delete=django.db.models.deletion.CASCADE, to='education.gradeclass', verbose_name='Класс'),
        ),
    ]
