# Generated by Django 4.2.3 on 2023-08-09 11:09

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='login',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='login',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.gradeclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='gradeclass',
            name='class_number',
            field=models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=2, verbose_name='Номер класса'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade_class',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('бел.яз', 'белорусский язык'), ('рус.яз', 'русский язык'), ('англ.яз', 'английский язык'), ('бел.лит', 'белорусская литература'), ('рус.лит', 'русская литература'), ('матем', 'математика'), ('ист', 'история'), ('био', 'биология'), ('гео', 'география'), ('физ', 'физика'), ('инф', 'информатика'), ('общ', 'обществоведение'), ('хим', 'химия')], max_length=100, verbose_name='Название предмета'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фото')),
                ('sex', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='Пол')),
                ('groups', models.ManyToManyField(blank=True, related_name='education_users', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='education_users', to='auth.permission', verbose_name='Права доступа')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='pupil',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to='education.user'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='education.user'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_class',
            field=models.ManyToManyField(to='education.gradeclass', verbose_name='Класс'),
        ),
    ]
