# Generated by Django 4.2.3 on 2023-08-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_user_grade_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade_class',
            field=models.ForeignKey(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='1', on_delete=django.db.models.deletion.PROTECT, to='education.gradeclass', verbose_name='Класс'),
        ),
    ]
