# Generated by Django 4.2.3 on 2023-08-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_studentmessage_delete_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='education.teacher', verbose_name='Получатель'),
        ),
    ]
