# Generated by Django 4.2.3 on 2023-08-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='pupil',
        ),
        migrations.RemoveField(
            model_name='gradeachievement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.user', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='gradeachievement',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.user', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_class',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='education.gradeclass', verbose_name='Класс',
                                    null=True)
        ),
        migrations.DeleteModel(
            name='Pupil',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
