# Generated by Django 4.2.3 on 2023-07-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_gradeclass_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeclass',
            name='class_number',
            field=models.CharField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], max_length=2, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='grade_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.gradeclass', verbose_name='Класс'),
        ),
    ]
