# Generated by Django 4.2.3 on 2023-08-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_user_grade_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.gradeclass', verbose_name='Номер класса'),
        ),
    ]
