# Generated by Django 4.2.3 on 2023-07-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_gradeclass_class_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='sex',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('яз', 'язык'), ('лит', 'литература'), ('матем', 'математика'), ('ист', 'история'), ('био', 'биология'), ('гео', 'география'), ('физ', 'физика'), ('инф', 'информатика'), ('общ', 'обществоведение'), ('хим', 'химия')], max_length=100, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='пол'),
        ),
    ]
