# Generated by Django 4.2.3 on 2023-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_teacher_remove_assignment_topic_delete_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade_class',
            field=models.ManyToManyField(to='education.gradeclass', verbose_name='Класс'),
        ),
    ]
