# Generated by Django 4.2.3 on 2023-07-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_pupil_sex_alter_subject_name_alter_teacher_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('бел.яз', 'белорусский язык'), ('рус.яз', 'русский язык'), ('англ.яз', 'английский язык'), ('бел.лит', 'белорусская литература'), ('рус.лит', 'русская литература'), ('матем', 'математика'), ('ист', 'история'), ('био', 'биология'), ('гео', 'география'), ('физ', 'физика'), ('инф', 'информатика'), ('общ', 'обществоведение'), ('хим', 'химия')], max_length=100, verbose_name='Название предмета'),
        ),
    ]
