# Generated by Django 4.2.3 on 2023-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_assignment_grade_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Фото'),
        ),
    ]
