# Generated by Django 4.2.3 on 2023-08-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('lesson', models.CharField(max_length=100)),
            ],
        ),
    ]
