# Generated by Django 4.2.3 on 2023-08-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ManyToManyField(max_length=100, to='education.subject'),
        ),
    ]
