# Generated by Django 4.2.3 on 2023-08-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_rename_number_schedule_lesson_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_number',
            field=models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='', max_length=10),
        ),
    ]
