# Generated by Django 4.2.3 on 2023-08-22 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_alter_schedule_class_number_alter_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
