# Generated by Django 4.2.3 on 2023-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_alter_schedule_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ManyToManyField(choices=[('бел.яз', 'белорусский язык'), ('рус.яз', 'русский язык'), ('англ.яз', 'английский язык'), ('бел.лит', 'белорусская литература'), ('рус.лит', 'русская литература'), ('матем', 'математика'), ('ист', 'история'), ('био', 'биология'), ('гео', 'география'), ('физ', 'физика'), ('инф', 'информатика'), ('общ', 'обществоведение'), ('хим', 'химия')], max_length=100, to='education.subject', verbose_name='Название предмета'),
        ),
    ]
