# Generated by Django 4.2.3 on 2023-08-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_alter_schedule_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/files/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/images/', verbose_name='Изображение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('assignments', models.ManyToManyField(related_name='submissions', to='education.assignment', verbose_name='Задания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Отправка ученика',
                'verbose_name_plural': 'Отправки учеников',
            },
        ),
    ]
